import React, { useState } from 'react';
import BrowserOnly from '@docusaurus/BrowserOnly';

// English to Urdu dictionary for robotics and AI terms
const englishToUrduDictionary = {
  // Common words
  'hello': 'ہیلو',
  'world': 'دنیا',
  'book': 'کتاب',
  'robot': 'روبوٹ',
  'humanoid': 'ہیومنوائڈ',
  'ai': 'مصنوعی ذہانت',
  'artificial intelligence': 'مصنوعی ذہانت',
  'perception': 'ادراک',
  'navigation': 'نیویگیشن',
  'mapping': 'نقشہ سازی',
  'physics': 'طبیعیات',
  'robotics': 'روبوٹکس',
  'engineering': 'انجینئرنگ',
  'technology': 'ٹیکنالوجی',
  'science': 'سائنس',
  'computer': 'کمپیٹر',
  'programming': 'پروگرامنگ',
  'software': 'سافٹ ویئر',
  'hardware': 'ہارڈ ویئر',
  'sensor': 'سینسر',
  'actuator': 'ایکچویٹر',
  'control': 'کنٹرول',
  'motion': 'حرکت',
  'movement': 'حرکت',
  'locomotion': 'لاکوموشن',
  'autonomous': 'خود مختار',
  'intelligent': 'ذہین',
  'smart': 'چالاک',
  'system': 'سسٹم',
  'algorithm': 'الگورتھم',
  'data': 'ڈیٹا',
  'learning': 'سیکھنا',
  'machine': 'مشین',
  'neural': 'نیورل',
  'network': 'نیٹ ورک',
  'vision': 'وژن',
  'camera': 'کیمرہ',
  'laser': 'لیزر',
  'lidar': 'لیڈار',
  'radar': 'ریڈار',
  'gps': 'جی پی ایس',
  'imu': 'آئی ایم یو',
  'accelerometer': 'ایکسلیرومیٹر',
  'gyroscope': 'جائراسکوپ',
  'magnetometer': 'میگنیٹومیٹر',
  'processor': 'پروسیسر',
  'microcontroller': 'مائیکرو کنٹرولر',
  'microprocessor': 'مائیکرو پروسیسر',
  'memory': 'میموری',
  'storage': 'اسٹوریج',
  'battery': 'بیٹری',
  'power': 'توانائی',
  'energy': 'توانائی',
  'wireless': 'وائرلیس',
  'communication': 'مواصلات',
  'protocol': 'پروٹوکول',
  'wifi': 'وائی فائی',
  'bluetooth': 'بلو ٹوتھ',
  'ethernet': 'ایتھرنیٹ',
  'internet': 'انٹرنیٹ',
  'cloud': 'کلاؤڈ',
  'server': 'سرور',
  'client': 'کلائنٹ',
  'application': 'ایپلی کیشن',
  'mobile': 'موبائل',
  'desktop': 'ڈیسک ٹاپ',
  'web': 'ویب',
  'interface': 'انٹرفیس',
  'user': 'صارف',
  'design': 'ڈیزائن',
  'experience': 'تجربہ',
  'performance': 'کارکردگی',
  'efficiency': 'کارآمدی',
  'optimization': 'بہترین کارکردگی',
  'simulation': 'سمولیشن',
  'real': 'حقیقی',
  'virtual': 'مجازی',
  'augmented': 'Augmented',
  'reality': 'ریلیٹی',
  'vr': 'VR',
  'ar': 'AR',
  'mixed': 'Mixed',
  'reality': 'ریلیٹی',
  'environment': 'ماحول',
  'space': 'خلا',
  'time': 'وقت',
  'motion': 'موشن',
  'velocity': 'رفتار',
  'acceleration': 'ایکسلریشن',
  'force': 'فورس',
  'torque': 'ٹارک',
  'mass': 'ماس',
  'weight': 'ویجٹ',
  'gravity': 'گریویٹی',
  'friction': 'فرکشن',
  'collision': 'کولیژن',
  'dynamics': 'ڈائنامکس',
  'kinematics': 'کنیمیٹکس',
  'statics': 'سٹیٹکس',
  'mechanics': 'میکانکس',
  'materials': 'مواد',
  'metals': 'دھاتیں',
  'polymers': 'پولیمرز',
  'composites': 'کمپوزٹس',
  'manufacturing': 'manufacturing',
  'assembly': 'اسمبلی',
  'integration': 'انٹیگریشن',
  'testing': 'ٹیسٹنگ',
  'validation': 'توثیق',
  'verification': 'توثیق',
  'quality': 'کوالٹی',
  'safety': 'سیفٹی',
  'security': 'سیکیورٹی',
  'reliability': 'قابل اعتمادی',
  'maintenance': 'مینٹیننس',
  'repair': 'مرمت',
  'upgrade': 'اپ گریڈ',
  'evolution': 'اے وولوشن',
  'future': 'مستقبل',
  'trends': 'رجحانات',
  'research': 'ریسرچ',
  'development': 'ڈویلپمنٹ',
  'innovation': 'نوآوری',
  'progress': 'پیشرفت',
  'success': 'کامیابی',
  'challenge': 'چیلنج',
  'problem': 'مسئلہ',
  'solution': 'حل',
  'approach': 'انداز',
  'method': 'طریقہ',
  'technique': 'ٹیکنیک',
  'strategy': 'حکمت عملی',
  'goal': 'هدف',
  'objective': 'مقصد',
  'purpose': 'مقصد',
  'function': 'فنکشن',
  'role': 'رول',
  'task': 'کام',
  'activity': 'سرگرمی',
  'process': 'عمل',
  'operation': 'آپریشن',
  'procedure': 'طریقہ کار',
  'step': 'قدم',
  'phase': 'مرحلہ',
  'stage': ' stadium',
  'level': 'لیول',
  'degree': 'ڈگری',
  'scale': 'سکیل',
  'range': 'رینج',
  'scope': 'دائرہ کار',
  'extent': 'حد',
  'limit': 'حد',
  'boundary': 'بارڈر',
  'constraint': 'پابندی',
  'requirement': 'ضرورت',
  'specification': 'مخصوص',
  'standard': 'سٹینڈرڈ',
  'protocol': 'پروٹوکول',
  'rule': 'رول',
  'law': 'قانون',
  'principle': 'اصول',
  'theory': 'نظریہ',
  'concept': ' notion',
  'idea': 'خیال',
  'thought': 'سوچ',
  'mind': 'دل',
  'brain': 'دماغ',
  'cognition': 'ادراک',
  'awareness': 'آگاہی',
  'consciousness': 'شعور',
  'intelligence': 'ذہانت',
  'wisdom': 'دانا',
  'knowledge': 'علم',
  'information': 'معلومات',
  'data': 'ڈیٹا',
  'fact': 'حقیقت',
  'truth': 'سچ',
  'reality': ' حقیقت',
  'existence': 'وجود',
  'being': 'ہونا',
  'life': 'زندگی',
  'living': 'زندہ',
  'organism': ' organism',
  'biology': 'بائیولوجی',
  'chemistry': 'کیمسٹری',
  'physics': 'فزکس',
  'mathematics': 'ریاضی',
  'geometry': 'جیومیٹری',
  'algebra': 'الجبر',
  'calculus': 'کیلکولس',
  'statistics': 'اعداد و شمار',
  'probability': 'احتمال',
  'logic': 'منطق',
  'philosophy': 'فلسفہ',
  'ethics': 'اخلاق',
  'morality': 'اخلاق',
  'values': 'قدریں',
  'culture': ' ثقافت',
  'society': ' سوسائٹی',
  'community': 'کمیونٹی',
  'family': ' خاندان',
  'home': ' گھر',
  'work': ' کام',
  'job': ' نوکری',
  'career': 'کیریئر',
  'education': ' تعلیم',
  'learning': ' سیکھنا',
  'teaching': ' سکھانا',
  'student': ' طالب علم',
  'teacher': ' استاد',
  'school': ' اسکول',
  'university': ' یونیورسٹی',
  'college': ' کالج',
  'institute': ' ادارہ',
  'academy': ' اکیڈمی',
  'library': ' لائبریری',
  'study': ' مطالعہ',
  'research': ' تحقیق',
  'experiment': ' تجربہ',
  'laboratory': ' لیب',
  'lab': ' لیب',
  'equipment': ' سامان',
  'tool': ' اوزار',
  'instrument': ' آلات',
  'device': 'ڈیوائس',
  'machine': ' مشین',
  'system': ' سسٹم',
  'component': ' جزو',
  'part': ' حصہ',
  'element': ' عنصر',
  'unit': ' یونٹ',
  'structure': ' ساخت',
  'form': ' فارم',
  'shape': ' شکل',
  'size': ' سائز',
  'dimension': ' طول و عرض',
  'volume': ' والیوم',
  'area': ' رقبہ',
  'length': ' لمبائی',
  'width': ' چوڑائی',
  'height': ' اونچائی',
  'depth': ' گہرائی',
  'distance': ' فاصلہ',
  'angle': ' اینگل',
  'direction': ' سمت',
  'orientation': ' سمت شناسی',
  'position': ' مقام',
  'location': ' جگہ',
  'place': ' جگہ',
  'space': ' خلا',
  'environment': ' ماحول',
  'surroundings': ' ارد گرد',
  'atmosphere': ' فضا',
  'climate': ' موسم',
  'weather': ' موسم',
  'temperature': ' درجہ حرارت',
  'pressure': ' دباؤ',
  'humidity': ' نمی',
  'light': ' روشني',
  'sound': ' آواز',
  'noise': ' آواز',
  'vibration': ' کمپن',
  'wave': ' لہر',
  'frequency': ' فریکوینسی',
  'amplitude': ' ایمپلی ٹوڈ',
  'wavelength': ' طول موج',
  'energy': ' توانائی',
  'power': ' توانائی',
  'work': ' کام',
  'heat': ' گرمی',
  'cold': ' سردی',
  'hot': ' گرم',
  'warm': ' گرما',
  'cool': ' ٹھنڈا',
  'fire': ' آگ',
  'water': ' پانی',
  'air': ' ہوا',
  'earth': ' زمین',
  'metal': ' دھات',
  'wood': ' لکڑی',
  'stone': ' پتھر',
  'glass': ' شیشہ',
  'plastic': ' پلاسٹک',
  'rubber': ' ربر',
  'fabric': ' کپڑا',
  'paper': ' کاغذ',
  'ink': ' سیاہی',
  'color': ' رنگ',
  'red': ' لال',
  'blue': ' نیلا',
  'green': ' سبز',
  'yellow': ' پیلا',
  'orange': ' نارنجی',
  'purple': ' جامنی',
  'pink': ' گلابی',
  'brown': ' بھورا',
  'black': ' کالا',
  'white': ' سفید',
  'gray': ' گray',
  'silver': ' چاندی',
  'gold': ' سونا',
  'large': ' بڑا',
  'small': ' چھوٹا',
  'big': ' بڑا',
  'little': ' چھوٹا',
  'tall': ' لمبا',
  'short': ' چھوٹا',
  'long': ' لمبا',
  'wide': ' چوڑا',
  'narrow': ' تنگ',
  'thick': ' موٹا',
  'thin': ' پتلا',
  'heavy': ' بھاری',
  'light': ' ہلکا',
  'fast': ' تیز',
  'slow': ' سست',
  'quick': ' تیز',
  'rapid': ' تیز',
  'speed': ' رفتار',
  'time': ' وقت',
  'now': ' اب',
  'then': ' پھر',
  'today': ' آج',
  'tomorrow': ' کل',
  'yesterday': ' گزشتہ',
  'past': ' گزشتہ',
  'present': ' موجودہ',
  'future': ' مستقبل',
  'before': ' پہلے',
  'after': ' بعد',
  'during': ' دوران',
  'while': ' جب',
  'until': ' جب تک',
  'since': ' از',
  'when': ' جب',
  'where': ' کہاں',
  'why': ' کیوں',
  'how': ' کیسے',
  'what': ' کیا',
  'which': ' کون',
  'who': ' کون',
  'whom': ' کس',
  'whose': ' کس',
  'any': ' کوئی',
  'some': ' کچھ',
  'many': ' بہت',
  'much': ' بہت',
  'few': ' کم',
  'several': ' کئی',
  'all': ' سب',
  'every': ' ہر',
  'each': ' ہر',
  'none': ' کوئی نہیں',
  'no': ' نہیں',
  'not': ' نہیں',
  'yes': ' ہاں',
  'okay': ' ٹھیک ہے',
  'ok': ' ٹھیک ہے',
  'good': ' اچھا',
  'bad': ' بری',
  'better': ' بہتر',
  'best': ' بہترین',
  'worse': ' بدتر',
  'worst': ' بدترین',
  'right': ' درست',
  'wrong': ' غلط',
  'true': ' سچ',
  'false': ' جھوٹ',
  'real': ' حقیقی',
  'fake': ' جعلی',
  'natural': ' قدرتی',
  'artificial': ' مصنوعی',
  'human': ' انسان',
  'animal': ' جانور',
  'plant': ' پودا',
  'tree': ' درخت',
  'flower': ' پھول',
  'fruit': ' پھل',
  'vegetable': ' سبزی',
  'food': ' کھانا',
  'drink': ' پینا',
  'water': ' پانی',
  'juice': ' رس',
  'milk': ' دودھ',
  'bread': ' روٹی',
  'rice': ' چاول',
  'meat': ' گوشت',
  'fish': ' مچھلی',
  'chicken': ' مرغ',
  'egg': ' انڈا',
  'cheese': ' پنیر',
  'butter': ' مکھن',
  'sugar': ' چینی',
  'salt': ' نمک',
  'pepper': ' مرچ',
  'oil': ' تیل',
  'spice': ' مصالحہ',
  'herb': ' جڑی بوٹی',
  'tea': ' چائے',
  'coffee': ' کافی',
  'breakfast': ' ناشتہ',
  'lunch': ' دوپہر کا کھانا',
  'dinner': ' رات کا کھانا',
  'meal': ' کھانا',
  'eat': ' کھانا',
  'drink': ' پینا',
  'sleep': ' سونا',
  'rest': ' آرام',
  'work': ' کام',
  'play': ' کھیلنا',
  'fun': ' مزہ',
  'game': ' کھیل',
  'sport': ' کھیل',
  'exercise': ' ورزش',
  'health': ' صحت',
  'sick': ' بیمار',
  'well': ' اچھا',
  'happy': ' خوش',
  'sad': ' اداس',
  'angry': ' غصہ',
  'fear': ' ڈر',
  'love': ' محبت',
  'hate': ' نفرت',
  'like': ' پسند',
  'dislike': ' ناپسند',
  'want': ' چاہنا',
  'need': ' ضرورت',
  'have': ' رکھنا',
  'get': ' حاصل کرنا',
  'give': ' دینا',
  'take': ' لینا',
  'make': ' بنانا',
  'do': ' کرنا',
  'go': ' جانا',
  'come': ' آنا',
  'see': ' دیکھنا',
  'look': ' دیکھنا',
  'watch': ' دیکھنا',
  'listen': ' سننا',
  'hear': ' سننا',
  'speak': ' بولنا',
  'talk': ' بات کرنا',
  'say': ' کہنا',
  'tell': ' بتانا',
  'ask': ' پوچھنا',
  'answer': ' جواب',
  'think': ' سوچنا',
  'know': ' جاننا',
  'learn': ' سیکھنا',
  'understand': ' سمجھنا',
  'believe': ' ماننا',
  'feel': ' محسوس کرنا',
  'touch': ' چھونا',
  'smell': ' بو',
  'taste': ' چکھنا',
  'walk': ' چلنا',
  'run': ' دوڑنا',
  'jump': ' کودنا',
  'fly': ' اڑنا',
  'swim': ' تیرنا',
  'drive': ' چلانا',
  'ride': ' سواری',
  'sit': ' بیٹھنا',
  'stand': ' کھڑا',
  'lie': ' لیٹنا',
  'lay': ' لیٹنا',
  'open': ' کھولنا',
  'close': ' بند کرنا',
  'start': ' شروع',
  'stop': ' رکنا',
  'begin': ' شروع',
  'end': ' ختم',
  'finish': ' ختم',
  'continue': ' جاری',
  'pause': ' رکنا',
  'wait': ' انتظار',
  'help': ' مدد',
  'use': ' استعمال',
  'try': ' کوشش',
  'find': ' تلاش',
  'lose': ' کھونا',
  'win': ' جیتنا',
  'buy': ' خریدنا',
  'sell': ' فروخت',
  'pay': ' ادا کرنا',
  'cost': ' قیمت',
  'money': ' پیسہ',
  'price': ' قیمت',
  'cheap': ' سستا',
  'expensive': ' مہنگا',
  'free': ' مفت',
  'house': ' گھر',
  'room': ' کمرہ',
  'door': ' دروازہ',
  'window': ' دریچہ',
  'wall': ' دیوار',
  'floor': ' فرش',
  'ceiling': ' چھت',
  'bed': ' بستر',
  'table': ' ٹیبل',
  'chair': ' کرسی',
  'sofa': ' سو فا',
  'kitchen': ' رساو',
  'bathroom': ' باتھ روم',
  'toilet': ' ٹوائلٹ',
  'garden': ' باغ',
  'park': ' پارک',
  'street': ' سڑک',
  'road': ' سڑک',
  'car': ' کار',
  'bus': ' بس',
  'train': ' ٹرین',
  'plane': ' ہوائی جہاز',
  'boat': ' کشتی',
  'ship': ' جہاز',
  'city': ' شہر',
  'town': ' شہر',
  'village': ' گاؤں',
  'country': ' ملک',
  'state': ' ریاست',
  'region': ' علاقہ',
  'continent': ' براعظم',
  'ocean': ' سمندر',
  'sea': ' سمندر',
  'river': ' دریا',
  'lake': ' جھیل',
  'mountain': ' پہاڑ',
  'hill': ' ٹیلہ',
  'valley': ' وادی',
  'forest': ' جنگل',
  'desert': ' صحراء',
  'island': ' جزیرہ',
  'bridge': ' پل',
  'building': ' عمارت',
  'office': ' دفتر',
  'shop': ' دکان',
  'store': ' سٹور',
  'market': ' بازار',
  'bank': ' بینک',
  'hospital': ' ہسپتال',
  'hotel': ' ہوٹل',
  'restaurant': ' ریسٹورانٹ',
  'school': ' اسکول',
  'university': ' یونیورسٹی',
  'college': ' کالج',
  'institute': ' ادارہ',
  'academy': ' اکیڈمی',
  'library': ' لائبریری',
  'museum': ' میوزیم',
  'theater': ' تھیATER',
  'cinema': ' سنیما',
  'church': ' چرچ',
  'temple': ' مندر',
  'mosque': ' مسجد',
  'synagogue': ' عبادت گاہ',
  'government': ' حکومت',
  'politics': ' سیاست',
  'election': ' انتخاب',
  'vote': ' ووٹ',
  'president': ' صدر',
  'minister': ' منسٹر',
  'ministry': ' وزارت',
  'department': ' محکمہ',
  'policy': ' پالیسی',
  'law': ' قانون',
  'court': ' عدالت',
  'judge': ' جج',
  'police': ' پولیس',
  'army': ' فوج',
  'navy': ' نیوی',
  'air force': ' ایئر فورس',
  'war': ' جنگ',
  'peace': ' امن',
  'business': ' کاروبار',
  'company': ' کمپنی',
  'corporation': ' کارپوریشن',
  'employee': ' ملازم',
  'employer': ' مالک',
  'manager': ' منیجر',
  'worker': ' کارکن',
  'customer': ' گاہک',
  'client': ' گاہک',
  'product': ' مصنوعات',
  'service': ' سروس',
  'industry': ' صنعت',
  'market': ' مارکیٹ',
  'trade': ' تجارت',
  'commerce': ' تجارت',
  'finance': ' مالیات',
  'economy': ' معیشت',
  'economics': ' معاشیات',
  'stock': ' اسٹاک',
  'investment': ' سرمایہ',
  'insurance': ' انشورنس',
  'tax': ' ٹیکس',
  'income': ' آمدنی',
  'expense': ' اخراجات',
  'profit': ' منافع',
  'loss': ' نقصان',
  'debt': ' قرض',
  'credit': ' کریڈٹ',
  'loan': ' قرض',
  'interest': ' سود',
  'currency': ' کرنسی',
  'dollar': ' ڈالر',
  'euro': ' یورو',
  'pound': ' پونڈ',
  'rupee': ' روپیہ',
  'yen': ' ین',
  'computer': ' کمپیوٹر',
  'phone': ' فون',
  'mobile': ' موبائل',
  'tablet': ' ٹیبلیٹ',
  'internet': ' انٹرنیٹ',
  'email': ' ای میل',
  'website': ' ویب سائٹ',
  'web': ' ویب',
  'online': ' آن لائن',
  'offline': ' آف لائن',
  'digital': ' ڈیجیٹل',
  'analog': ' اینا لوگ',
  'software': ' سافٹ ویئر',
  'hardware': ' ہارڈ ویئر',
  'program': ' پروگرام',
  'application': ' ایپلیکیشن',
  'app': ' ایپ',
  'game': ' گیم',
  'music': ' موسیقی',
  'video': ' ویڈیو',
  'photo': ' تصویر',
  'picture': ' تصویر',
  'image': ' تصویر',
  'text': ' متن',
  'word': ' لفظ',
  'sentence': ' جملہ',
  'paragraph': ' پیرا',
  'page': ' صفحہ',
  'book': ' کتاب',
  'novel': ' ناول',
  'story': ' کہانی',
  'article': ' مضمون',
  'news': ' خبریں',
  'magazine': ' رسالہ',
  'newspaper': ' اخبار',
  'journal': ' جریدہ',
  'report': ' رپورٹ',
  'document': ' دستاویز',
  'letter': ' خط',
  'mail': ' میل',
  'post': ' پوسٹ',
  'delivery': ' ترسیل',
  'transport': ' نقل و حمل',
  'shipping': ' شپنگ',
  'logistics': ' لا جسٹکس',
  'supply': ' سپلائی',
  'chain': ' زنجیر',
  'management': ' مینجمنٹ',
  'organization': ' تنظیم',
  'team': ' ٹیم',
  'group': ' گروپ',
  'meeting': ' میٹنگ',
  'conference': ' کانفرنس',
  'presentation': ' پیش کاری',
  'speech': ' تقریر',
  'lecture': ' لیکچر',
  'discussion': ' بحث',
  'conversation': ' گفتگو',
  'dialogue': ' گفتگو',
  'debate': ' بحث',
  'argument': ' دلیل',
  'opinion': ' رائے',
  'idea': ' خیال',
  'thought': ' سوچ',
  'belief': ' عقیدہ',
  'faith': ' ایمان',
  'religion': ' مذہب',
  'spiritual': ' روحانی',
  'philosophy': ' فلسفہ',
  'science': ' سائنس',
  'research': ' تحقیق',
  'study': ' مطالعہ',
  'analysis': ' تجزیہ',
  'theory': ' نظریہ',
  'hypothesis': ' نظریہ',
  'experiment': ' تجربہ',
  'observation': ' مشاہدہ',
  'measurement': ' پیمائش',
  'data': ' ڈیٹا',
  'result': ' نتیجہ',
  'finding': ' تلاش',
  'discovery': ' دریافت',
  'invention': ' ایجاد',
  'innovation': ' نو آوری',
  'technology': ' ٹیکنالوجی',
  'engineering': ' انجینئرنگ',
  'mathematics': ' ریاضی',
  'physics': ' فزکس',
  'chemistry': ' کیمسٹری',
  'biology': ' بائیولوجی',
  'geology': ' جیولوجی',
  'astronomy': ' اسٹرونومی',
  'medicine': ' دوا',
  'health': ' صحت',
  'disease': ' بیماری',
  'treatment': ' علاج',
  'doctor': ' ڈاکٹر',
  'nurse': ' نرس',
  'patient': ' مریض',
  'hospital': ' ہسپتال',
  'clinic': ' کلینک',
  'pharmacy': ' فارمیسی',
  'medicine': ' دوا',
  'drug': ' دوا',
  'therapy': ' تھراپی',
  'surgery': ' سرجری',
  'operation': ' آپریشن',
  'anesthesia': ' اینستھیسیا',
  'recovery': ' صحت یابی',
  'rehabilitation': ' بحالی',
  'fitness': ' فٹ نیس',
  'exercise': ' ورزش',
  'nutrition': ' غذائیت',
  'diet': ' ڈائیٹ',
  'vitamin': ' وٹامن',
  'protein': ' پروٹین',
  'carbohydrate': ' کاربوہائیڈریٹ',
  'fat': ' چربی',
  'mineral': ' معدنی',
  'water': ' پانی',
  'sleep': ' سونا',
  'rest': ' آرام',
  'energy': ' توانائی',
  'strength': ' طاقت',
  'power': ' توانائی',
  'force': ' قوت',
  'motion': ' حرکت',
  'movement': ' حرکت',
  'speed': ' رفتار',
  'velocity': ' رفتار',
  'acceleration': ' ایکسلریشن',
  'mass': ' ماس',
  'weight': ' وزن',
  'density': ' گھنDensity',
  'volume': ' والیوم',
  'area': ' رقبہ',
  'length': ' لمبائی',
  'distance': ' فاصلہ',
  'time': ' وقت',
  'duration': ' مدت',
  'frequency': ' فریکوینسی',
  'period': ' مدت',
  'temperature': ' درجہ حرارت',
  'pressure': ' دباؤ',
  'volume': ' والیوم',
  'capacity': ' صلاحیت',
  'quantity': ' مقدار',
  'amount': ' مقدار',
  'number': ' نمبر',
  'count': ' گنتی',
  'sum': ' جمع',
  'difference': ' فرق',
  'product': ' ضرب',
  'quotient': ' قسم',
  'fraction': ' کسر',
  'decimal': ' اعشاریہ',
  'percentage': ' فیصد',
  'ratio': ' تناسب',
  'proportion': ' تناسب',
  'equation': ' مساوات',
  'formula': ' فارمولہ',
  'function': ' فنکشن',
  'variable': ' متغیر',
  'constant': ' مستقل',
  'zero': ' صفر',
  'one': ' ایک',
  'two': ' دو',
  'three': ' تین',
  'four': ' چار',
  'five': ' پانچ',
  'six': ' چھ',
  'seven': ' سات',
  'eight': ' آٹھ',
  'nine': ' نو',
  'ten': ' دس',
  'eleven': ' گیارہ',
  'twelve': ' بارہ',
  'thirteen': ' تیرہ',
  'fourteen': ' چودہ',
  'fifteen': ' پندرہ',
  'sixteen': ' سولہ',
  'seventeen': ' سترہ',
  'eighteen': ' اٹھارہ',
  'nineteen': ' انیس',
  'twenty': ' بیس',
  'thirty': ' تیس',
  'forty': ' چالیس',
  'fifty': ' پچاس',
  'sixty': ' ساٹھ',
  'seventy': ' ستر',
  'eighty': ' اسی',
  'ninety': ' نوے',
  'hundred': ' سو',
  'thousand': ' ہزار',
  'million': ' ملین',
  'billion': ' بلین',
  'trillion': ' ٹریلین',
  'first': ' پہلا',
  'second': ' دوسرا',
  'third': ' تیسرا',
  'fourth': ' چوتھا',
  'fifth': ' پانچواں',
  'sixth': ' چھٹا',
  'seventh': ' ساتواں',
  'eighth': ' آٹھواں',
  'ninth': ' نواں',
  'tenth': ' دہواں',
  'once': ' ایک بار',
  'twice': ' دو بار',
  'again': ' دوبارہ',
  'more': ' مزید',
  'less': ' کم',
  'most': ' زیادہ تر',
  'least': ' کم ترین',
  'every': ' ہر',
  'each': ' ہر',
  'all': ' سب',
  'none': ' کوئی نہیں',
  'some': ' کچھ',
  'any': ' کوئی',
  'many': ' بہت',
  'much': ' بہت',
  'few': ' کم',
  'little': ' کم',
  'several': ' کئی',
  'various': ' مختلف',
  'different': ' مختلف',
  'same': ' ایک جیسا',
  'similar': ' مماثل',
  'like': ' جیسا',
  'as': ' جیسا',
  'than': ' سے',
  'equal': ' برابر',
  'unequal': ' نابرابر',
  'greater': ' بڑا',
  'lesser': ' چھوٹا',
  'bigger': ' بڑا',
  'smaller': ' چھوٹا',
  'higher': ' اونچا',
  'lower': ' نیچا',
  'larger': ' بڑا',
  'nearer': ' قریب',
  'farther': ' دور',
  'further': ' دور',
  'inside': ' اندر',
  'outside': ' باہر',
  'above': ' اوپر',
  'below': ' نیچے',
  'over': ' اوپر',
  'under': ' نیچے',
  'between': ' درمیان',
  'among': ' درمیان',
  'around': ' چاروں طرف',
  'through': ' ذریعہ',
  'across': ' پار',
  'along': ' ساتھ',
  'toward': ' طرف',
  'away': ' دور',
  'forward': ' آگے',
  'backward': ' پیچھے',
  'up': ' اوپر',
  'down': ' نیچے',
  'in': ' میں',
  'out': ' باہر',
  'on': ' پر',
  'off': ' بند',
  'at': ' پر',
  'by': ' کے ذریعہ',
  'with': ' کے ساتھ',
  'without': ' کے بغیر',
  'for': ' کے لیے',
  'to': ' کو',
  'from': ' سے',
  'about': ' کے بارے',
  'of': ' کا',
  'and': ' اور',
  'or': ' یا',
  'but': ' لیکن',
  'if': ' اگر',
  'then': ' تو',
  'else': ' ورنہ',
  'when': ' جب',
  'where': ' کہاں',
  'why': ' کیوں',
  'how': ' کیسے',
  'what': ' کیا',
  'which': ' کون',
  'who': ' کون',
  'whom': ' کس',
  'whose': ' کس',
  'can': ' سکتا ہے',
  'could': ' سکتا تھا',
  'may': ' ہوسکتا ہے',
  'might': ' ہوسکتا تھا',
  'must': ' ضرور',
  'should': ' چاہیے',
  'would': ' کرے گا',
  'will': ' کرے گا',
  'shall': ' کروں گا',
  'do': ' کرنا',
  'does': ' کرتا ہے',
  'did': ' کیا',
  'have': ' رکھنا',
  'has': ' رکھتا ہے',
  'had': ' رکھتا تھا',
  'be': ' ہونا',
  'is': ' ہے',
  'am': ' ہوں',
  'are': ' ہیں',
  'was': ' تھا',
  'were': ' تھے',
  'been': ' ہوا',
  'being': ' ہونا',
  'go': ' جانا',
  'went': ' گیا',
  'gone': ' چلا گیا',
  'come': ' آنا',
  'came': ' آیا',
  'taken': ' لیا',
  'made': ' بنایا',
  'done': ' کیا',
  'seen': ' دیکھا',
  'known': ' جانا',
  'given': ' دیا',
  'found': ' ملا',
  'said': ' کہا',
  'told': ' بتایا',
  'asked': ' پوچھا',
  'answered': ' جواب دیا',
  'thought': ' سوچا',
  'felt': ' محسوس کیا',
  'heard': ' سنا',
  'saw': ' دیکھا',
  'looked': ' دیکھا',
  'watched': ' دیکھا',
  'listened': ' سنا',
  'spoken': ' بولا',
  'talked': ' بات کی',
  'worked': ' کام کیا',
  'played': ' کھیلا',
  'used': ' استعمال کیا',
  'tried': ' کوشش کی',
  'called': ' پکارا',
  'needed': ' ضرورت تھی',
  'wanted': ' چاہا',
  'liked': ' پسند کیا',
  'loved': ' محبت کی',
  'hated': ' نفرت کی',
  'helped': ' مدد کی',
  'bought': ' خریدا',
  'sold': ' فروخت کیا',
  'paid': ' ادا کیا',
  'cost': ' قیمت',
  'built': ' بنایا',
  'written': ' لکھا',
  'read': ' پڑھا',
  'learned': ' سیکھا',
  'taught': ' سکھایا',
  'studied': ' پڑھا',
  'examined': ' جانچا',
  'tested': ' ٹیسٹ کیا',
  'measured': ' پیما کیا',
  'calculated': ' حساب کیا',
  'computed': ' کمپیوٹ کیا',
  'analyzed': ' تجزیہ کیا',
  'evaluated': ' جانچ کی',
  'assessed': ' جانچ کی',
  'judged': ' فیصلہ کیا',
  'considered': ' سوچا',
  'regarded': ' سمجھا',
  'treated': ' سلوک کیا',
  'handled': ' سنبھالا',
  'managed': ' منظم کیا',
  'controlled': ' کنٹرول کیا',
  'operated': ' چلایا',
  'executed': ' انجام دیا',
  'performed': ' انجام دیا',
  'accomplished': ' مکمل کیا',
  'achieved': ' حاصل کیا',
  'completed': ' مکمل کیا',
  'finished': ' ختم کیا',
  'ended': ' ختم کیا',
  'terminated': ' ختم کیا',
  // Robotics-specific terms
  'ros': 'ROS (Robot Operating System)',
  'ros2': 'ROS 2',
  'nodes': 'نیڈز',
  'topics': 'ٹاپکس',
  'services': 'سروسز',
  'actions': 'ایکشنز',
  'publishers': 'پبلشرز',
  'subscribers': 'سبسکرائبرز',
  'qos': 'QoS (Quality of Service)',
  'urdf': 'URDF (Unified Robot Description Format)',
  'gazebo': 'گزیبو (Simulation Environment)',
  'rviz': 'RViz (Robot Visualization)',
  'slam': 'SLAM (Simultaneous Localization and Mapping)',
  'computer vision': 'کمپیوٹر وژن',
  'path planning': 'راہ کی منصوبہ بندی',
  'kinematics': 'کنیمیٹکس',
  'dynamics': 'ڈائی نامکس',
  'forward kinematics': 'فرورڈ کنیمیٹکس',
  'inverse kinematics': 'انورس کنیمیٹکس',
  'trajectory': 'ٹریجکٹری',
  'control theory': 'کنٹرول تھیوری',
  'pid controller': 'PID کنٹرولر',
  'state estimation': 'اسٹیٹ اسٹیمیشن',
  'kalman filter': 'کیلمان فلٹر',
  'particle filter': 'پارٹیکل فلٹر',
  'reinforcement learning': 'رینفورسمنٹ لرننگ',
  'machine learning': 'مشین لرننگ',
  'deep learning': 'ڈیپ لرننگ',
  'neural network': 'نیورل نیٹ ورک',
  'computer vision': 'کمپیوٹر وژن',
  'sensor fusion': 'سینسر فیوژن',
  'imu': 'IMU (Inertial Measurement Unit)',
  'lidar': 'لیڈار',
  'stereo vision': 'سٹیریو وژن',
  'monocular vision': 'مونوکولر وژن',
  'manipulator': 'مینیپولیٹر',
  'end effector': 'اینڈ ایفیکٹر',
  'joint space': 'جائنٹ سپیس',
  'cartesian space': 'کارٹیشن سپیس',
  'jacobian': 'جیکوبین',
  'holonomic': 'ہولونومک',
  'non-holonomic': 'نون ہولونومک',
  'differential drive': 'ڈفرینشل ڈرائیو',
  'ackermann steering': 'ایکرمن سٹیرنگ',
  'locomotion': 'لوکوموشن',
  'bipedal': 'بائی پیڈل',
  'quadruped': 'کواڈروپیڈ',
  'gait': 'گیٹ',
  'walking': 'وکنگ',
  'stability': 'سٹیبیلٹی',
  'balance': 'بیلنس',
  'center of mass': 'سینٹر آف ماس',
  'zero moment point': 'زیرو مومنٹ پوائنٹ',
  'cpg': 'CPG (Central Pattern Generator)',
  'behavior tree': 'بیہیویئر ٹری',
  'finite state machine': 'فائنٹ سٹیٹ مشین',
  'path planning': 'پاتھ کی منصوبہ بندی',
  'a star algorithm': 'A* الگورتھم',
  'dijkstra algorithm': 'ڈیجکسٹرا الگورتھم',
  'rapidly exploring random tree': 'RRT (Rapidly Exploring Random Tree)',
  'potential field': 'پوٹینشل فیلڈ',
  'occupancy grid': 'اکوپینسی گرڈ',
  'amcl': 'AMCL (Adaptive Monte Carlo Localization)',
  'move base': 'موو بیس',
  'navigation stack': 'نیویگیشن اسٹیک',
  'tf': 'TF (Transforms)',
  'robotics middleware': 'روبوٹکس مڈل ویئر',
  'hardware abstraction layer': 'ہارڈ ویئر ابسٹریکشن لیئر',
  'real-time system': 'ریل ٹائم سسٹم',
  'embedded system': 'ایمبیڈیڈ سسٹم',
  'microcontroller': 'مائکرو کنٹرولر',
  'fpga': 'FPGA (Field Programmable Gate Array)',
  'raspberry pi': 'ریسبیری پائی',
  'arduino': 'آرڈوینو',
  'computer vision': 'کمپیوٹر وژن',
  'opencv': 'OpenCV',
  'image processing': 'ایمیج پروسیسنگ',
  'feature detection': 'فیچر ڈیٹیکشن',
  'object recognition': 'آبجیکٹ ریکوگنیشن',
  'tracking': 'ٹریکنگ',
  'stereo matching': 'سٹیریو میچنگ',
  'structure from motion': 'سٹرکچر فرام موشن',
  'visual odometry': 'وژل اوڈومیٹری',
  'aruco markers': 'اروکو مارکرز',
  'aruco': 'اروکو',
  'apriltag': 'ایپرل ٹیگ',
  'point cloud': 'پوائنٹ کلاؤڈ',
  'pcl': 'PCL (Point Cloud Library)',
  'mesh': 'میش',
  '3d reconstruction': '3D ریکنسرکشن',
  'humanoid robot': 'ہیومنوائڈ روبوٹ',
  'bipedal walking': 'بائی پیڈل واکنگ',
  'inverse kinematics': 'انورس کنیمیٹکس',
  'forward kinematics': 'فرورڈ کنیمیٹکس',
  'footstep planning': 'فٹ سٹیپ پلاننگ',
  'walking pattern': 'وکنگ پیٹرن',
  'balance control': 'بیلنس کنٹرول',
  'zero moment point': 'زیرو مومنٹ پوائنٹ',
  'angular momentum': 'اینگولر مومنٹم',
  'com': 'COM (Center of Mass)',
  'whole body control': 'ہول بڈی کنٹرول',
  'motion planning': 'موشن پلاننگ',
  'trajectory generation': 'ٹریجکٹری جنریشن',
  'task space': 'ٹاسک سپیس',
  'operational space': 'آپریشنل سپیس',
  'force control': 'فورس کنٹرول',
  'impedance control': 'امپیڈینس کنٹرول',
  'admittance control': 'ایڈمیٹنس کنٹرول',
  'compliant control': 'کمپلائينٹ کنٹرول',
  'ros packages': 'ROS پیکجز',
  'rclpy': 'rclpy (Python Client Library)',
  'rclcpp': 'rclcpp (C++ Client Library)',
  'message types': 'میسج ٹائپس',
  'service types': 'سروس ٹائپس',
  'action types': 'ایکشن ٹائپس',
  'launch files': 'لاؤنچ فائلز',
  'parameter server': 'پیرامیٹر سرور',
  'ros master': 'ROS ماسٹر',
  'roscore': 'ROS Core',
  'rosbag': 'ROS Bag',
  'urdf': 'URDF',
  'xacro': 'Xacro',
  'rviz': 'RViz',
  'gazebo': 'Gazebo',
  'moveit': 'MoveIt',
  'navigation': 'نیویگیشن',
  'slam': 'SLAM',
  'gmapping': 'G-Mapping',
  'cartographer': 'کارٹو گرافر',
  'octomap': 'اکٹو میپ',
  'costmap': 'کوست میپ',
  'global planner': 'گلوبل پلانر',
  'local planner': 'لوکل پلانر',
  'teb local planner': 'TEB لوکل پلانر',
  'dwa local planner': 'DWA لوکل پلانر',
  'robot state publisher': 'روبوٹ اسٹیٹ پبلشر',
  'joint state publisher': 'جائنٹ اسٹیٹ پبلشر',
  'tf2': 'TF2',
  'robotics operating system': 'روبوٹکس آپریٹنگ سسٹم',
  'real world robotics': 'ریل ورلڈ روبوٹکس',
  'simulation': 'سمولیشن',
  'digital twin': 'ڈیجیٹل ٹوئن',
  'hardware in the loop': 'ہارڈ ویئر ان دا لُوپ',
  'software in the loop': 'سافٹ ویئر ان دا لُوپ',
  'robotic arm': 'روبوٹک آرم',
  'mobile robot': 'موبائل روبوٹ',
  'wheeled robot': 'وہیلڈ روبوٹ',
  'legged robot': 'لیگڈ روبوٹ',
  'flying robot': 'فلائینگ روبوٹ',
  'underwater robot': 'انڈر ووٹر روبوٹ',
  'robotics research': 'روبوٹکس ریسرچ',
  'robotics industry': 'روبوٹکس انڈسٹری',
  'human robot interaction': 'ہیومن روبوٹ انٹر ایکشن',
  'hri': 'HRI (Human Robot Interaction)',
  'collaborative robots': 'کولیبؤریٹو روبوٹس',
  'cobots': 'کوبوٹس',
  'industrial robotics': 'انڈسٹریل روبوٹکس',
  'service robotics': 'سروس روبوٹکس',
  'medical robotics': 'میڈیکل روبوٹکس',
  'surgical robotics': 'سرجریکل روبوٹکس',
  'rehabilitation robotics': 'ری ہیبیلی ٹیشن روبوٹکس',
  'assistive robotics': 'ایسٹسٹو روبوٹکس',
  'agricultural robotics': 'ایگریکلچرل روبوٹکس',
  'field robotics': 'فیلڈ روبوٹکس',
  'space robotics': 'سپیس روبوٹکس',
  'underwater robotics': 'انڈر ووٹر روبوٹکس',
  'search and rescue robotics': 'سرچ اینڈ ریسکیو روبوٹکس',
  'military robotics': 'میلیٹری روبوٹکس',
  'defense robotics': 'ڈیفینس روبوٹکس',
  'autonomous systems': 'آٹونومس سسٹم',
  'embodied intelligence': 'ایم بیوڈیڈ انٹیلی جنس',
  'physical ai': 'فیزیکل اے آئی',
  'vision language action': 'وژن لینگویج ایکشن',
  'vla': 'VLA (Vision Language Action)',
  'large action model': 'لارج ایکشن ماڈل',
  'lam': 'LAM (Large Action Model)',
  'visuomotor': 'ویزوو موٹر',
  'multimodal': 'ملٹی ماڈل',
  'cross modal': 'کراس موڈل',
  'robot learning': 'روبوٹ لرننگ',
  'imitation learning': 'ایمیٹیشن لرننگ',
  'learning from demonstration': 'لرننگ فرام ڈیموں سٹریشن',
  'robot programming': 'روبوٹ پروگرامنگ',
  'robot control': 'روبوٹ کنٹرول',
  'motion control': 'موشن کنٹرول',
  'force control': 'فورس کنٹرول',
  'impedance control': 'امپیڈینس کنٹرول',
  'admittance control': 'ایڈمیٹنس کنٹرول',
  'robot dynamics': 'روبوٹ ڈائینمکس',
  'robot kinematics': 'روبوٹ کنیمیٹکس',
  'robot calibration': 'روبوٹ کیلیبریشن',
  'robot safety': 'روبوٹ سیفٹی',
  'robot security': 'روبوٹ سکیورٹی',
  'robot ethics': 'روبوٹ ایتھکس',
  'robot standards': 'روبوٹ اسٹینڈرڈز',
  'iso standards': 'ISO اسٹینڈرڈز',
  'robot testing': 'روبوٹ ٹیسٹنگ',
  'robot validation': 'روبوٹ والیڈیشن',
  'robot verification': 'روبوٹ ویریفکیشن',
  'robot reliability': 'روبوٹ ریلیبیلٹی',
  'robot maintenance': 'روبوٹ مینٹیننس',
  'robot repair': 'روبوٹ ریپئر',
  'robot upgrade': 'روبوٹ اپ گریڈ',
  'robot evolution': 'روبوٹ ای وولوشن',
  'robot future': 'روبوٹ فیچر',
  'robot trends': 'روبوٹ ٹرینڈز',
  'robot innovation': 'روبوٹ ای نوویشن',
  'robot progress': 'روبوٹ پروگریس',
  'robot success': 'روبوٹ سکسیس',
  'robot challenge': 'روبوٹ چیلنج',
  'robot problem': 'روبوٹ پرالیم',
  'robot solution': 'روبوٹ سولوشن',
  'robot approach': 'روبوٹ ایپروچ',
  'robot method': 'روبوٹ میتھڈ',
  'robot technique': 'روبوٹ ٹیکنیق',
  'robot strategy': 'روبوٹ سٹریٹیجی',
  'robot goal': 'روبوٹ گوئل',
  'robot objective': 'روبوٹ آبجیکٹو',
  'robot purpose': 'روبوٹ پرپوز',
  'robot function': 'روبوٹ فنکشن',
  'robot role': 'روبوٹ رول',
  'robot task': 'روبوٹ ٹاسک',
  'robot activity': 'روبوٹ ایکٹیویٹی',
  'robot process': 'روبوٹ پروسیس',
  'robot operation': 'روبوٹ آپریشن',
  'robot procedure': 'روبوٹ پروسیجر',
  'robot step': 'روبوٹ سٹیپ',
  'robot phase': 'روبوٹ فیز',
  'robot stage': 'روبوٹ سٹیج',
  'robot level': 'روبوٹ لیول',
  'robot degree': 'روبوٹ ڈگری',
  'robot scale': 'روبوٹ سکیل',
  'robot range': 'روبوٹ رینج',
  'robot scope': 'روبوٹ سکوپ',
  'robot extent': 'روبوٹ ایکسٹینٹ',
  'robot limit': 'روبوٹ لیمیٹ',
  'robot boundary': 'روبوٹ باؤنڈری',
  'robot constraint': 'روبوٹ کن سٹرینٹ',
  'robot requirement': 'روبوٹ ریکوائرمینٹ',
  'robot specification': 'روبوٹ سپیسیفکیشن',
  'robot standard': 'روبوٹ اسٹینڈرڈ',
  'robot protocol': 'روبوٹ پروٹوکول',
  'robot rule': 'روبوٹ رول',
  'robot law': 'روبوٹ لا',
  'robot principle': 'روبوٹ پرنسیپل',
  'robot theory': 'روبوٹ تھیوری',
  'robot concept': 'روبوٹ کانسیپٹ',
  'robot idea': 'روبوٹ ایڈیا',
  'robot thought': 'روبوٹ آوٹ',
  'robot mind': 'روبوٹ مائنڈ',
  'robot brain': 'روبوٹ برین',
  'robot cognition': 'روبوٹ کوگنیشن',
  'robot perception': 'روبوٹ ادراک',
  'robot awareness': 'روبوٹ ایئر نیس',
  'robot consciousness': 'روبوٹ کانسیوس نیس',
  'robot intelligence': 'روبوٹ انٹیلی جنس',
  'robot wisdom': 'روبوٹ ویزم',
  'robot knowledge': 'روبوٹ نالیج',
  'robot information': 'روبوٹ انفارمیشن',
  'robot data': 'روبوٹ ڈیٹا',
  'robot fact': 'روبوٹ فیکٹ',
  'robot truth': 'روبوٹ ٹروتھ',
  'robot reality': 'روبوٹ رئیلٹی',
  'robot existence': 'روبوٹ ایکسیسٹینس',
  'robot being': 'روبوٹ بیئنگ',
  'robot life': 'روبوٹ لائف',
  'robot living': 'روبوٹ لیوئنگ',
  'robot organism': 'روبوٹ آرگنیزم',
  'robot biology': 'روبوٹ بایولوجی',
  'robot chemistry': 'روبوٹ کیمسٹری',
  'robot physics': 'روبوٹ فزکس',
  'robot mathematics': 'روبوٹ میتھمیٹیکس',
};

// Function to translate a single word or phrase
const translateWord = (word) => {
  // First, try exact match
  if (englishToUrduDictionary[word.toLowerCase()]) {
    return englishToUrduDictionary[word.toLowerCase()];
  }

  // Then, try matching individual words if it's a phrase
  const words = word.split(' ');
  if (words.length > 1) {
    return words.map(w => englishToUrduDictionary[w.toLowerCase()] || w).join(' ');
  }

  return word; // Return original if no translation found
};

export default function EnglishUrduTranslator() {
  const [inputText, setInputText] = useState('');
  const [outputText, setOutputText] = useState('');
  const [translationMode, setTranslationMode] = useState('en-to-ur'); // 'en-to-ur' or 'ur-to-en'

  const handleTranslate = () => {
    if (!inputText.trim()) {
      setOutputText('');
      return;
    }

    if (translationMode === 'en-to-ur') {
      // English to Urdu translation
      const words = inputText.split(/\b/); // Split by word boundaries to preserve spaces
      let translated = '';
      
      for (const word of words) {
        if (word.trim() && !/^\s+$/.test(word)) {
          translated += translateWord(word);
        } else {
          translated += word; // Preserve spaces/punctuation
        }
      }
      
      setOutputText(translated);
    } else {
      // Urdu to English (would require reverse dictionary)
      setOutputText("Urdu to English translation is not currently available.");
    }
  };

  const handleSwap = () => {
    // Swap input and output, and change translation mode
    setInputText(outputText);
    setOutputText(inputText);
    setTranslationMode(translationMode === 'en-to-ur' ? 'ur-to-en' : 'en-to-ur');
  };

  const handleClear = () => {
    setInputText('');
    setOutputText('');
  };

  return (
    <BrowserOnly>
      {() => (
        <div style={containerStyle}>
          <div style={headerStyle}>
            <h2 style={titleStyle}>English to Urdu Translator</h2>
            <p style={subtitleStyle}>Translate robotics and AI terminology between English and Urdu</p>
          </div>

          <div style={contentStyle}>
            <div style={modeSelectorStyle}>
              <button 
                style={modeButtonStyle(translationMode === 'en-to-ur')} 
                onClick={() => setTranslationMode('en-to-ur')}
              >
                English to Urdu
              </button>
              <button 
                style={modeButtonStyle(translationMode === 'ur-to-en')} 
                onClick={() => setTranslationMode('ur-to-en')}
              >
                Urdu to English
              </button>
            </div>

            <div style={inputContainerStyle}>
              <label style={labelStyle}>Input Text:</label>
              <textarea
                value={inputText}
                onChange={(e) => setInputText(e.target.value)}
                placeholder={translationMode === 'en-to-ur' 
                  ? 'Enter English text to translate to Urdu...' 
                  : 'Enter Urdu text to translate to English...'}
                style={textareaStyle}
                rows="4"
              />
            </div>

            <div style={buttonContainerStyle}>
              <button onClick={handleTranslate} style={translateButtonStyle}>
                Translate
              </button>
              <button onClick={handleSwap} style={swapButtonStyle}>
                ↔ Swap
              </button>
              <button onClick={handleClear} style={clearButtonStyle}>
                Clear
              </button>
            </div>

            <div style={outputContainerStyle}>
              <label style={labelStyle}>Translated Text:</label>
              <div style={outputStyle}>
                {outputText || <span style={placeholderStyle}>Translation will appear here...</span>}
              </div>
            </div>
          </div>
        </div>
      )}
    </BrowserOnly>
  );
}

/* ======== STYLES ======== */
const containerStyle = {
  maxWidth: '800px',
  margin: '0 auto',
  padding: '20px',
  fontFamily: 'Arial, sans-serif',
};

const headerStyle = {
  textAlign: 'center',
  marginBottom: '30px',
};

const titleStyle = {
  fontSize: '24px',
  color: '#2c3e50',
  margin: '0 0 10px 0',
};

const subtitleStyle = {
  fontSize: '16px',
  color: '#7f8c8d',
  margin: '0',
};

const contentStyle = {
  background: '#fff',
  border: '1px solid #ddd',
  borderRadius: '8px',
  padding: '20px',
  boxShadow: '0 2px 10px rgba(0,0,0,0.1)',
};

const modeSelectorStyle = {
  display: 'flex',
  justifyContent: 'center',
  marginBottom: '20px',
};

const modeButtonStyle = (isActive) => ({
  backgroundColor: isActive ? '#0057ff' : '#f8f9fa',
  color: isActive ? 'white' : '#333',
  border: '1px solid #ddd',
  padding: '8px 16px',
  cursor: 'pointer',
  borderRadius: '4px',
  fontSize: '14px',
  fontWeight: 'bold',
  outline: 'none',
  transition: 'all 0.3s ease',
  margin: '0 5px',
});

const inputContainerStyle = {
  marginBottom: '20px',
};

const labelStyle = {
  display: 'block',
  fontWeight: 'bold',
  marginBottom: '5px',
  color: '#2c3e50',
};

const textareaStyle = {
  width: '100%',
  padding: '10px',
  fontSize: '16px',
  border: '1px solid #ddd',
  borderRadius: '4px',
  resize: 'vertical',
  fontFamily: 'inherit',
  boxSizing: 'border-box',
};

const buttonContainerStyle = {
  display: 'flex',
  justifyContent: 'center',
  gap: '10px',
  marginBottom: '20px',
};

const translateButtonStyle = {
  backgroundColor: '#0057ff',
  color: 'white',
  border: 'none',
  padding: '10px 20px',
  borderRadius: '4px',
  cursor: 'pointer',
  fontWeight: 'bold',
  fontSize: '16px',
  transition: 'background-color 0.3s ease',
};

const swapButtonStyle = {
  backgroundColor: '#4CAF50',
  color: 'white',
  border: 'none',
  padding: '10px 15px',
  borderRadius: '4px',
  cursor: 'pointer',
  fontWeight: 'bold',
  fontSize: '16px',
  transition: 'background-color 0.3s ease',
};

const clearButtonStyle = {
  backgroundColor: '#f44336',
  color: 'white',
  border: 'none',
  padding: '10px 15px',
  borderRadius: '4px',
  cursor: 'pointer',
  fontWeight: 'bold',
  fontSize: '16px',
  transition: 'background-color 0.3s ease',
};

const outputContainerStyle = {
  marginTop: '20px',
};

const outputStyle = {
  padding: '15px',
  border: '1px solid #ddd',
  borderRadius: '4px',
  backgroundColor: '#f9f9f9',
  minHeight: '60px',
  fontSize: '16px',
  lineHeight: '1.5',
};

const placeholderStyle = {
  color: '#999',
  fontStyle: 'italic',
};