openapi: 3.0.0
info:
  title: Isaac Sim RAG Chatbot API
  description: API for the Retrieval-Augmented Generation chatbot that answers questions about Isaac Sim and humanoid robotics
  version: 1.0.0
servers:
  - url: https://api.isaac-sim-book.com/v1
    description: Production server
  - url: https://staging-api.isaac-sim-book.com/v1
    description: Staging server

paths:
  /chat:
    post:
      summary: Chat with the Isaac Sim expert
      description: Submit a question about Isaac Sim, humanoid robotics, or related topics and receive an answer with citations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Response from the Isaac Sim expert
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /search:
    post:
      summary: Search Isaac Sim documentation
      description: Search through the Isaac Sim book content to find relevant information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRequest'
      responses:
        '200':
          description: Search results from Isaac Sim documentation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
        '400':
          description: Invalid search request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /modules:
    get:
      summary: Get list of available modules
      description: Retrieve information about all Isaac Sim book modules
      responses:
        '200':
          description: List of available modules
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModuleListResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's question about Isaac Sim or humanoid robotics
          example: "How do I set up a camera sensor in Isaac Sim?"
        context:
          type: string
          description: Optional context to constrain the response to a specific module
          example: "module-1-ros2"
        session_id:
          type: string
          description: Optional session ID to maintain conversation context
          example: "sess-abc123"

    ChatResponse:
      type: object
      required:
        - response
        - sources
        - confidence
      properties:
        response:
          type: string
          description: The chatbot's answer to the question
          example: "To set up a camera sensor in Isaac Sim, you first need to create a Camera prim..."
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          description: List of sources used to generate the response
        confidence:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Confidence score for the response (0.0-1.0)
          example: 0.95
        follow_up_questions:
          type: array
          items:
            type: string
          description: Suggested follow-up questions based on the response
          example: [
            "What are the different camera types available?",
            "How do I calibrate the camera intrinsic parameters?"
          ]

    SearchRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The search query for Isaac Sim documentation
          example: "humanoid robot navigation Isaac Sim"
        filters:
          type: object
          properties:
            module:
              type: string
              description: Filter search to specific module
              example: "module-3-nvidia-isaac"
            content_type:
              type: string
              enum: [tutorial, reference, example, api]
              description: Filter by content type
          description: Optional filters to narrow search results
        limit:
          type: integer
          minimum: 1
          maximum: 50
          default: 10
          description: Maximum number of results to return

    SearchResponse:
      type: object
      required:
        - results
        - total_count
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/SearchResult'
          description: List of search results
        total_count:
          type: integer
          description: Total number of matching results
        query_time_ms:
          type: number
          format: float
          description: Time taken to execute the search in milliseconds

    SearchResult:
      type: object
      required:
        - id
        - title
        - content
        - module
        - relevance_score
      properties:
        id:
          type: string
          description: Unique identifier for the content
        title:
          type: string
          description: Title of the content section
        content:
          type: string
          description: Snippet of the matching content
        module:
          type: string
          description: Module where the content is located
        section:
          type: string
          description: Specific section within the module
        relevance_score:
          type: number
          format: float
          minimum: 0.0
          maximum: 1.0
          description: Relevance score for the search result
        url:
          type: string
          format: uri
          description: URL to the full content

    Source:
      type: object
      required:
        - title
        - module
        - section
        - url
      properties:
        title:
          type: string
          description: Title of the source document
          example: "Setting up Camera Sensors in Isaac Sim"
        module:
          type: string
          description: Module where the information is located
          example: "module-2-digital-twin"
        section:
          type: string
          description: Specific section within the module
          example: "camera-sensor-setup"
        url:
          type: string
          format: uri
          description: URL to the source content
          example: "https://isaac-sim-book.com/docs/module-2-digital-twin/camera-sensor-setup"

    Module:
      type: object
      required:
        - id
        - title
        - number
        - description
      properties:
        id:
          type: string
          description: Unique identifier for the module
          example: "module-1-ros2"
        title:
          type: string
          description: Title of the module
          example: "Module 1: The Robotic Nervous System (ROS 2)"
        number:
          type: integer
          description: Sequential module number
          example: 1
        description:
          type: string
          description: Brief description of the module content
          example: "Introduction to ROS 2 concepts for humanoid robot control"
        word_count:
          type: integer
          description: Approximate word count of the module
          example: 1350
        references_count:
          type: integer
          description: Number of references in the module
          example: 7

    ModuleListResponse:
      type: object
      required:
        - modules
      properties:
        modules:
          type: array
          items:
            $ref: '#/components/schemas/Module'
          description: List of all available modules

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error code
          example: "INVALID_QUERY"
        message:
          type: string
          description: Human-readable error message
          example: "Query parameter is required and cannot be empty"
        details:
          type: object
          description: Additional error details (optional)
          example: {"param": "query"}

tags:
  - name: chat
    description: Chat with Isaac Sim expert
  - name: search
    description: Search Isaac Sim documentation
  - name: modules
    description: Module information

security:
  - api_key: []

securityDefinitions:
  api_key:
    type: apiKey
    name: X-API-Key
    in: header